### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by thethiny** [AltimorTASDK/dfpslayer#2]
Hi,
I tried to lookup your contact info but I didn't find any. I just wanted to thank you so much for this as it allowed me to be able to write assembly in x64 targets (which AFAIK isn't possible). Thank you for the VirtualProtect(char array) method that you used in dfpslayer, thank you a lot!

**Comment by AltimorTASDK** [comment]
Good to hear my code was useful. 

You can also add the masm build target to your project in VS and keep your assembly in separate files, which is what I'd normally recommend. You can see an example in this project: https://github.com/AltimorTASDK/dbfzhitboxes

dfpslayer uses a byte array + VirtualProtect because I took the bytes from a routine in mvci.exe.

**Comment by thethiny** [comment]
This is exactly what I did as well. I took the bytes from a routine in MK11.exe but I added a little bit to the start and end of it. I will definitely take a look at the masm method. Thanks again!
